### ISSUE TITLE
create_database explodes

### ISSUE THREAD

**Issue by matti** [influxdata/influxdb-ruby#237] opened 2020-01-29 15:23 UTC
```
  require "influxdb"
  influxdb_database = "default"
  influxdb = InfluxDB::Client.new influxdb_database, host: "influxdb"
  influxdb.create_database(influxdb_database)
```

```
Traceback (most recent call last):
	6: from test.rb:367:in `<main>'
	5: from /var/lib/gems/2.5.0/gems/influxdb-0.7.0/lib/influxdb/query/database.rb:5:in `create_database'
	4: from /var/lib/gems/2.5.0/gems/influxdb-0.7.0/lib/influxdb/query/core.rb:133:in `execute'
	3: from /var/lib/gems/2.5.0/gems/influxdb-0.7.0/lib/influxdb/client/http.rb:11:in `get'
	2: from /var/lib/gems/2.5.0/gems/influxdb-0.7.0/lib/influxdb/client/http.rb:53:in `connect_with_retry'
	1: from /var/lib/gems/2.5.0/gems/influxdb-0.7.0/lib/influxdb/client/http.rb:19:in `block in get'
/var/lib/gems/2.5.0/gems/influxdb-0.7.0/lib/influxdb/client/http.rb:86:in `resolve_error': {"error":"error parsing query: found DEFAULT, expected identifier at line 1, char 17"} (InfluxDB::Error)
```

**Comment by russorat** [comment] 2020-01-29 17:34
@matti thanks for the issue. I think the issue might be with `default` being a reserved word in influxql:

```
➜  chronograf git:(master) ✗ influx
Connected to http://localhost:8086 version v1.7.9
InfluxDB shell version: v1.7.9
> create database default
ERR: error parsing query: found DEFAULT, expected identifier at line 1, char 17
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> create database not_default
> show databases
name: databases
name
----
_internal
telegraf
not_default
>
```

i opened this issue to update the docs: https://github.com/influxdata/docs.influxdata.com/issues/2606

**Comment by Esity** [comment] 2020-04-29 14:13
Closing this since it is a feature not a bug 😉 
In all seriousness, thanks for reporting this

**Closed by Esity** 2020-04-29 14:13 UTC
